### ISSUE TITLE
Broken Link in the read me

### ISSUE THREAD

**Issue by benkoshy** [elm-lang/time#13]
In the README.md, the following sentence exists:

> "Go here for a little example application that uses time. It can help you get everything hooked up in practice!"

- The link attached to the word "here" is broken. Unfortunately, I don't know where it should point to, so I cannot put in a PR.

**Comment by olpeh** [comment]
I think it should point here: https://guide.elm-lang.org/effects/time.html

Edit: as #12 seems to fix this

**Comment by benkoshy** [comment]
@olpeh chrs, will close this issue.
