### ISSUE TITLE
No way to set parts of the Posix value yet

### ISSUE THREAD

**Issue by ChristophP** [elm-lang/time#2]
For some use cases it would be useful to be able to set certain parts to of the date as well. For example if there is a dropdown where times or days are picked from. Whenever you select something you wanna set the hour or day on the current posix value.
![image](https://user-images.githubusercontent.com/5880236/37373195-f1b8b664-2715-11e8-974d-ba67bd19864a.png)

So for every `toX` function there could be a corresponding `setX` function like this:

```elm
setHour : Zone -> Int -> Posix -> Posix
setHour zone hour time =
    posixToMillis time
        + ((hour - toHour zone time) * 3600000)
        |> millisToPosix

-- use it like this
t = millisToPosix 3600000
toHour utc t == 1
setHour utc 2 |> toHour utc == 2 
```

**Comment by evancz** [comment]
This is not a published library. I don't think it makes sense to make feature requests at this time.

**Comment by aecay** [comment]
Now that the library is published, it would be good to look at this again.
