### ISSUE TITLE
Info: TC39 is working on IANA Database browser support proposal

### ISSUE THREAD

**Issue by ChristophP** [elm-lang/time#23]
As mentioned in the docs of this package.
> *Future Note*: We can improve here when there is good browser support for JavaScript functions that (1) expose the IANA time zone database and (2) let you ask the time zone of the computer. The committee that reviews additions to JavaScript is called TC39, and I encourage you to push for these capabilities! I cannot do it myself unfortunately.

TC39 is working on a proposal for an API that would give access to the IANA Timezone Database.
https://github.com/tc39/proposal-temporal#temporaltimezone

**Comment by evancz** [comment]
I've heard about this! It's very exciting! We'll want to wait until it is finalized and starts showing up in a decent amount of browsers out in the wild though.
